### ISSUE TITLE
Error after "enter location"

### ISSUE THREAD

**Issue by XVR1212** [klpod221/linkedin-connect-bot#1]
filled all the fields in ".env"
installed all requirements

it doesn't open the chrome like it should
instead I'm getting this error:

```
Traceback (most recent call last):
  File "c:\Users\Sahar\Desktop\Shit But Importent\linkedin-connect-bot\main.py", line 110, in <module>
    driver = webdriver.Chrome(service=s, options=options)
  File "C:\Users\Sahar\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__       
    super().__init__(
  File "C:\Users\Sahar\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 61, in __init__     
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\Sahar\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 209, in __init__      
    self.start_session(capabilities)
  File "C:\Users\Sahar\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 293, in start_session 
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\Sahar\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute       
    self.error_handler.check_response(response)
  File "C:\Users\Sahar\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
        GetHandleVerifier [0x00007FF78FAE2142+3514994]
        (No symbol) [0x00007FF78F700CE2]
        (No symbol) [0x00007FF78F5A76AA]
        (No symbol) [0x00007FF78F5D9850]
        (No symbol) [0x00007FF78F5D7F52]
        (No symbol) [0x00007FF78F620AB4]
        (No symbol) [0x00007FF78F615D93]
        (No symbol) [0x00007FF78F5E4BDC]
        (No symbol) [0x00007FF78F5E5C64]
        GetHandleVerifier [0x00007FF78FB0E16B+3695259]
        GetHandleVerifier [0x00007FF78FB66737+4057191]
        GetHandleVerifier [0x00007FF78FB5E4E3+4023827]
        GetHandleVerifier [0x00007FF78F8304F9+689705]
        (No symbol) [0x00007FF78F70C048]
        (No symbol) [0x00007FF78F708044]
        (No symbol) [0x00007FF78F7081C9]
        (No symbol) [0x00007FF78F6F88C4]
        BaseThreadInitThunk [0x00007FFCFF447344+20]
        RtlUserThreadStart [0x00007FFD00D826B1+33]
```

**Comment by klpod221** [comment]
I haven't tried testing it on windows yet. But I realize that `chromedriver` also needs to know where chrome is. So i add `binary_location` options for windows.
[commit](https://github.com/klpod221/linkedin-connect-bot/commit/84431dc6b8eab310fc3a975ea1a1f35e4e08ab2e)
![image](https://github.com/klpod221/linkedin-connect-bot/assets/62713126/57105042-7c09-44d3-b2b0-fab9f67fb3a7)

**Comment by XVR1212** [comment]
Thank you, I will check it out
